# Data Wrangling 
### (Also known as data munging or data preparation)

> Data wrangling is the process of cleaning, structuring and enriching raw data to be used in data science, machine learning (ML) and other data-driven applications. (IBM)

- Dealing with Missing Values
- Data Formatting
- Data Normalization
- Binning
- Removing Duplicates

#### Data wrangling focuses on preparing and cleaning the data to ensure its quality and usability, while EDA centers on exploring and understanding the data to extract meaningful insights.

# Let's Start

In [68]:
import numpy as np
import pandas as pd
import seaborn as sns

In [70]:
kashti = sns.load_dataset("titanic")
kashti.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [71]:
#mathematic operation
(kashti['age']+1).head(10)

0    23.0
1    39.0
2    27.0
3    36.0
4    36.0
5     NaN
6    55.0
7     3.0
8    28.0
9    15.0
Name: age, dtype: float64

In [72]:
kashti.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

## 1. Dealing with missing values
- types
    1. N/A
    2. NaN 
    3. 0
    4. Blank

- To handle these missing values:
  1. We can drop all values.
  2. We can replace the minning values with the mean of the whole column (for numeric)
  3. We can apply machine learning model like linear regression to train on this dataset and then predict the unknown or missing values.

In [73]:
kashti.shape

(891, 15)

In [74]:
# where exactly missing values are
kashti.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [75]:
#how to drop missing values:
kashti.dropna(subset = ['deck'], axis = 0, inplace  = True)
# inplace true means changes will be made in original dataset

In [76]:
kashti.shape

(203, 15)

In [77]:
kashti.isnull().sum()

survived        0
pclass          0
sex             0
age            19
sibsp           0
parch           0
fare            0
embarked        2
class           0
who             0
adult_male      0
deck            0
embark_town     2
alive           0
alone           0
dtype: int64

In [78]:
#all missing values dropped
kashti = kashti.dropna()
kashti.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           0
embark_town    0
alive          0
alone          0
dtype: int64

In [79]:
#now check how much data we are left with
kashti.shape

(182, 15)

In [80]:
ks_mean = sns.load_dataset("titanic")
ks_mean.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [82]:
ks_mean["age"].head(10)

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: age, dtype: float64

In [83]:
ks_mean['age'] = pd.to_numeric(ks_mean['age'])
age_avg = ks_mean['age'].mean()
ks_mean['age'].fillna(age_avg, inplace=True)
ks_mean[['age']].head(10)

C:\Users\Hp\AppData\Local\Temp\ipykernel_12420\3773180083.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ks_mean['age'].fillna(age_avg, inplace=True)

         age
0  22.000000
1  38.000000
2  26.000000
3  35.000000
4  35.000000
5  29.699118
6  54.000000
7   2.000000
8  27.000000
9  14.000000

In [84]:
ks_mean.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

## 2. Data Formatting

In [85]:
#know the datatype
kashti.dtypes

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

In [86]:
# convert age from years to days
kashti['age'] = kashti['age']*365
kashti.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,13870.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,12775.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,19710.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
10,1,3,female,1460.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,21170.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True

In [88]:
# convert datatype of any column
kashti['survived'] = kashti['survived'].astype("float64")
kashti.dtypes

survived        float64
pclass            int64
sex              object
age in days     float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

In [87]:
#rename column afterwards
kashti.rename(columns = {"age":"age in days"}, inplace  = True )
kashti.head()

,survived,pclass,sex,age in days,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,13870.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,12775.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,19710.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
10,1,3,female,1460.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,21170.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True

## 3. Data Normalization

In [89]:
kashti[["age in days","fare"]]

     age in days     fare
1        13870.0  71.2833
3        12775.0  53.1000
6        19710.0  51.8625
10        1460.0  16.7000
11       21170.0  26.5500
..           ...      ...
871      17155.0  52.5542
872      12045.0   5.0000
879      20440.0  83.1583
887       6935.0  30.0000
889       9490.0  30.0000

[182 rows x 2 columns]

#### 3.1 Simple Feature Scaling
 New  = (old) / old(max)

In [101]:
#simple feature scaling (values come in 0-1 range)
kashti['fare'] = kashti['fare']/kashti['fare'].max()
kashti['age in days'] = kashti['age in days']/kashti['age in days'].max()
kashti.head()

,survived,pclass,sex,age in days,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age_group
1,1.0,1,female,0.4750,1,0,-0.017619,C,First,woman,False,C,Cherbourg,yes,False,Jawan
3,1.0,1,female,0.4375,1,0,-0.059574,S,First,woman,False,C,Southampton,yes,False,Jawan
6,0.0,1,male,0.6750,0,0,-0.062429,S,First,man,True,E,Southampton,no,True,Burhay
10,1.0,3,female,0.0500,1,1,-0.143559,S,Third,child,False,G,Southampton,yes,False,Bachay
11,1.0,1,female,0.7250,0,0,-0.120832,S,First,woman,False,C,Southampton,yes,True,Burhay

#### 3.2 Min Max Normalization
 New  = [old - old(min)] / [old(max) - old(min)]

In [92]:
#Min - Max Method  
kashti['fare'] = (kashti['fare']-kashti['fare'].min())/(kashti['age in days'].max()-kashti['age in days'].min()) 
kashti['fare']

1      0.140754
3      0.104850
6      0.102407
10     0.032975
11     0.052425
         ...
871    0.103772
872    0.009873
879    0.164203
887    0.059237
889    0.059237
Name: fare, Length: 182, dtype: float64

#### 3.3 Z-Score Method
new = [old - old(mean)] / [old(std)]

In [94]:
# z- score method (range = -3 to 3)
kashti['fare'] = (kashti['fare']-kashti['fare'].mean())/kashti['fare'].std()
kashti['fare']

1     -0.099835
3     -0.337554
6     -0.353732
10    -0.813428
11    -0.684654
         ...
871   -0.344689
872   -0.966388
879    0.055413
887   -0.639551
889   -0.639551
Name: fare, Length: 182, dtype: float64

#### 3.4 Log Transformation

In [95]:
#log transformation
ks['fare'] = np.log(ks['fare'])
ks['fare'].head()

d:\anaconda\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

0    0.683603
1    1.450832
2    0.727559
3    1.379314
4    0.735091
Name: fare, dtype: float64

In [96]:
#fare value already gone very minimum that's why we'll load again and try different normalization methods
ks  = sns.load_dataset('titanic')
ks.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [97]:
#log transformation
ks['fare'] = np.log(ks['fare'])
ks['fare'].head()

d:\anaconda\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

0    1.981001
1    4.266662
2    2.070022
3    3.972177
4    2.085672
Name: fare, dtype: float64

## 4. Binning
- grouping of values into bins

In [54]:
#dummy values to categories 
pd.get_dummies(kashti['sex'])

     female   male
1      True  False
3      True  False
6     False   True
10     True  False
11     True  False
..      ...    ...
871    True  False
872   False   True
879    True  False
887    True  False
889   False   True

[182 rows x 2 columns]

In [98]:
bin_edges = [0, 0.33, 0.66, 1]
age_groups = ["Bachay", "Jawan", "Burhay"]

kashti['age_group'] = pd.cut(kashti['age in days'], bins=bin_edges, labels=age_groups)

kashti[['age in days', 'age_group']]

     age in days age_group
1         0.4750     Jawan
3         0.4375     Jawan
6         0.6750    Burhay
10        0.0500    Bachay
11        0.7250    Burhay
..           ...       ...
871       0.5875     Jawan
872       0.4125     Jawan
879       0.7000    Burhay
887       0.2375    Bachay
889       0.3250    Bachay

[182 rows x 2 columns]

## 5. Removing Duplicates

In [100]:
student_data = {'Name': ['Abdullah', 'Ans', 'Laiba', 
                         'Anam', 'Abd', 'Ans', 'Abd'],
 
                'Roll_no': [23, 54, 29, 54, 59, 38, 59],}
df = pd.DataFrame(student_data)
non_duplicate = df[~df.duplicated('Roll_no')]
non_duplicate

       Name  Roll_no
0  Abdullah       23
1       Ans       54
2     Laiba       29
4       Abd       59
5       Ans       38